services:
  - type: web
    name: case-study-app
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_MODEL
        value: gpt-5.1
      - key: OUT_DIR
        value: /tmp/out
